#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Configuration file for the SKA Namespace Manager documentation build.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# -- Project information -----------------------------------------------------
project = "SKA Namespace Manager"
copyright = "2019-2026 SKA Observatory"
author = "SKA System Team"

# The short X.Y.Z version.
version = '0.3.2'
# The full version, including alpha/beta/rc pre-release tags.
release = '0.3.2'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    "sphinx.ext.intersphinx",
    "sphinxcontrib.mermaid",
]

# Architecture and state diagrams are written as Mermaid source in the pages
# themselves, so they are reviewable in a diff and never drift from the code
# the way an exported image does.
#
# The theme switches between a light and a dark page background, but Mermaid
# renders a single SVG whichever mode the reader picked. The diagrams therefore
# carry their own palette (see the classDef blocks) and these variables pin the
# few colours a diagram cannot set itself - edge lines, edge labels and the
# default node/text colours - to that same light palette. _static/css/mermaid.css
# then keeps the surrounding card light in both modes so the contrast holds.
mermaid_init_js = """mermaid.initialize({
    startOnLoad: true,
    theme: "base",
    themeVariables: {
        background: "#ffffff",
        primaryColor: "#eef2f6",
        primaryTextColor: "#1c2b36",
        primaryBorderColor: "#8b98a5",
        lineColor: "#4a5560",
        textColor: "#1c2b36",
        edgeLabelBackground: "#ffffff",
        fontFamily: "'Noto Sans', sans-serif",
        fontSize: "15px"
    },
    flowchart: {
        // Wide enough that the explicit <br/> breaks in the node labels are
        // the only breaks; the default wraps them again mid-phrase.
        wrappingWidth: 320
    }
});"""

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = [".rst"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# README.md is a symlink to the repository README, kept for contributors
# browsing the source tree; the documentation content lives in the pages
# below and does not include it.
exclude_patterns = ["README.md"]

# -- Options for HTML output -------------------------------------------------

# The SKAO Sphinx theme carries the SKAO branding (logo, favicon, fonts and
# colours) and the skao-* directives used on the landing page, so no custom
# logo or favicon is registered here. The only custom stylesheet is the one
# that keeps the Mermaid diagrams legible in dark mode.
html_theme = "ska_ser_sphinx_theme"

html_css_files = ["css/mermaid.css"]

html_theme_options = {
    "logo": {
        "text": "SKA Namespace Manager",
    },
    "gitlab_url": "https://gitlab.com/ska-telescope/ska-ser-namespace-manager",
    "use_edit_page_button": True,
}

html_context = {
    "gitlab_url": "https://gitlab.com",
    "gitlab_user": "ska-telescope",
    "gitlab_repo": "ska-ser-namespace-manager",
    "gitlab_version": "main",
    "doc_path": "docs/src",
}

# Every documentation section is a single page, so the left "Section
# Navigation" sidebar has nothing to list. Section switching happens in the
# top navbar and within-page navigation in the right-hand "On this page"
# panel.
html_sidebars = {"**": []}

# Add any paths that contain custom static files (such as images) here,
# relative to this directory.
html_static_path = ["_static"]

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "skaosernamespacemanagerdoc"

# -- Options for intersphinx -------------------------------------------------

intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}
