image:
  repository: registry.gitlab.com/ska-telescope/ska-ser-namespace-manager/ska-ser-namespace-manager

api:
  config:
    people_database:
      enabled: false
      spreadsheet_id: "dummy"
      credentials:
        client_email: "dummy"
        client_id: "dummy"
        client_x509_cert_url: "dummy"
        private_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIBOgIBAAJBAKj34GkxFhD90vcNLYLInFEX6Ppy1tPf9Cnzj4p4WGeKLs1Pt8Qu
          KUpRKfFLfRYC9AIKjbJTWit+CqvjWYzvQwECAwEAAQJAIJLixBy2qpFoS4DSmoEm
          o3qGy0t6z09AIJtH+5OeRV1be+N4cDYJKffGzDa88vQENZiRm0GRq6a+HPGQMd2k
          TQIhAKMSvzIBnni7ot/OSie2TmJLY4SwTQAevXysE2RbFDYdAiEBCUEaRQnMnbp7
          9mxDXDf6AU0cN/RPBjb9qSHDcWZHGzUCIG2Es59z8ugGrDY+pxLQnwfotadxd+Uy
          v/Ow5T0q5gIJAiEAyS4RaI9YG8EWx/2w0T67ZUVAw8eOMB6BIUg0Xcu+3okCIBOs
          /5OiPgoTdSy7bcF9IGpSE8ZgGKzgYQVZeN97YE00
          -----END RSA PRIVATE KEY-----
        private_key_id: "dummy"
        project_id: "dummy"

actionController:
  config:
    namespaces:
      - names:
          - dummy-*
    notifier:
      token: null

collectController:
  config:
    namespaces:
      - names:
          - dummy-*
    people_api:
      insecure: true
