{{- if .Values.actionController.apiPriorityAndFairness }}
apiVersion: v1
kind: PriorityLevelConfiguration
metadata:
  name: {{ template "ska-ser-namespace-manager.action-controller.name" . }}
  labels:
    {{- include "ska-ser-namespace-manager.action-controller.labels" . | nindent 4 }}
{{- with .Values.actionController.priorityLevelConfigurationSpec }}
spec:
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
{{- end }}
