{{- if and (gt (int .Values.actionController.replicas) 1) .Values.actionController.config.leader_election.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ska-ser-namespace-manager.action-controller.leaderElectionVol" . }}
spec:
  storageClassName: {{ .Values.actionController.pvc.leaderElection.storageClassName }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
{{- end }}