apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ska-ser-namespace-manager.action-controller.configName" . }}
  namespace: {{ template "ska-ser-namespace-manager.namespace" . }}
  labels:
    {{- include "ska-ser-namespace-manager.action-controller.labels" . | nindent 4 }}
stringData:
  config.yml: |
    {{- include "ska-ser-namespace-manager.action-controller.config" . | nindent 4 }}
