apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-binding
subjects:
- kind: ServiceAccount
  name: controller-sa
  namespace: ska-ser-namespace-manager
roleRef:
  kind: ClusterRole
  name: controller-role
  apiGroup: rbac.authorization.k8s.io
