apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-namespace-{{namespace}}
  labels:
    manager.cicd.skao.int/managed_namespace: "{{namespace}}"
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ska-ser-namespace-manager-collect-controller-sa
          containers:
          - name: namespace-collector
            image: namespace-manager:latest
            imagePullPolicy: Never
            command:
            - "python"
            - "collector.py"
            - "--action"
            - "check_namespace"
            - "--namespace"
            - "{{namespace}}"
          restartPolicy: OnFailure
