{{- if and (gt (int .Values.collectController.replicas) 1) .Values.collectController.config.leader_election.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ska-ser-namespace-manager.collect-controller.leaderElectionVol" . }}
spec:
  storageClassName: {{ .Values.collectController.pvc.leaderElection.storageClassName }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
{{- end }}