apiVersion: v1
kind: Service
metadata:
  name: {{ include "ska-ser-namespace-manager.collect-controller.serviceName" . }}
  namespace: {{ include "ska-ser-namespace-manager.namespace" . }}
  labels:
    {{- include "ska-ser-namespace-manager.collect-controller.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 80
      protocol: TCP
      name: controller
  selector:
    {{- include "ska-ser-namespace-manager.collect-controller.matchLabels" . | nindent 4 }}
